# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

group:
  anne_remco:
    name: Anne Remco
    entities:
      - device_tracker.iphone_van_marietje_2
      - device_tracker.sm_f711b

proximity:
  home_anne:
    devices:
      - device_tracker.iphone_van_marietje_2
    tolerance: 50
    unit_of_measurement: km
  home_remco:
    devices:
      - device_tracker.sm_f711b
    tolerance: 50
    unit_of_measurement: km

command_line:
  - sensor:
      name: "Lines of Code"
      unique_id: lines_of_code
      command: "find /config -name '*.yaml' | xargs cat | wc -l"
      scan_interval: 20000

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

mqtt:
  sensor:
    name: "Water Verbruik Vorige Dag"
    state_topic: "zigbee2mqtt/ha/water_usage_daily"
    unit_of_measurement: L
