---
alias: Notify lowest price gas station
trigger:
  - platform: state
    entity_id: sensor.gas_station_euro95_lowest_price_1
action:
  - service: notify.mobile_app_iphone_van_remco
    data:
      title: Cheapest gas station
      message: 'Gas costs € {{ states.sensor.gas_station_euro95_lowest_price_1.state }} at {{ state_attr("sensor.gas_station_euro95_lowest_price_1","station_street") }}. '
      data:
        url: https://www.google.com/maps/search/?api=1&query={{ state_attr("sensor.gas_station_[fuel_type]_lowest_price_1","latitude") }},{{ state_attr("sensor.gas_station_euro95_lowest_price_1", "longitude") }}
